"""
Django settings for agendabarber project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--6_)n2&#eagrb2h9co*2&o3%&ohqi4%#aqwx^#a0ldq8k@w=wd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'unslippery-unruffledly-raylan.ngrok-free.dev']

# CSRF Configuration for ngrok
CSRF_TRUSTED_ORIGINS = [
    'https://unslippery-unruffledly-raylan.ngrok-free.dev',
    'http://localhost:8000',
    'http://127.0.0.1:8000'
]

# Session Configuration for external redirects
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_SAMESITE = 'Lax'  # Allow cross-site requests from MercadoPago
SESSION_SAVE_EVERY_REQUEST = True  # Keep session active


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'agendabarber',
    'panel'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'capstone.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'agendabarber.context_processors.user_type_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'capstone.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Santiago'  # Zona horaria de Chile

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Directorios de archivos estáticos
STATICFILES_DIRS = [
    BASE_DIR / 'agendabarber' / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ----------------------------------------------------------------------
# 💡 CONFIGURACIÓN DE AUTENTICACIÓN (LOGIN/LOGOUT)
# ----------------------------------------------------------------------

# Nombre de la URL de tu página de inicio (debe coincidir con el 'name' en urls.py)
LOGIN_REDIRECT_URL = 'inicio' 

# URL a la que se redirige después de cerrar sesión
LOGOUT_REDIRECT_URL = 'inicio' 

# Nombre de la URL para la página de login. Usamos 'login' que es la que Django genera
LOGIN_URL = 'login'

# ----------------------------------------------------------------------
# 💳 CONFIGURACIÓN DE MERCADOPAGO
# ----------------------------------------------------------------------

# MercadoPago Credentials
MERCADOPAGO_ACCESS_TOKEN = os.getenv('MERCADOPAGO_ACCESS_TOKEN')
MERCADOPAGO_PUBLIC_KEY = os.getenv('MERCADOPAGO_PUBLIC_KEY')
MERCADOPAGO_WEBHOOK_SECRET = os.getenv('MERCADOPAGO_WEBHOOK_SECRET')

# MercadoPago Environment (True for sandbox, False for production)
MERCADOPAGO_SANDBOX = os.getenv('MERCADOPAGO_SANDBOX', 'True').lower() == 'true'

# MercadoPago URLs
MERCADOPAGO_SUCCESS_URL = os.getenv('MERCADOPAGO_SUCCESS_URL', 'http://localhost:8000/payment/success/')
MERCADOPAGO_FAILURE_URL = os.getenv('MERCADOPAGO_FAILURE_URL', 'http://localhost:8000/payment/failure/')
MERCADOPAGO_PENDING_URL = os.getenv('MERCADOPAGO_PENDING_URL', 'http://localhost:8000/payment/pending/')
MERCADOPAGO_WEBHOOK_URL = os.getenv('MERCADOPAGO_WEBHOOK_URL', 'http://localhost:8000/webhooks/mercadopago/')

# Validation for required MercadoPago settings (only in production)
if not DEBUG and not MERCADOPAGO_ACCESS_TOKEN:
    raise ValueError("MERCADOPAGO_ACCESS_TOKEN environment variable is required")

# Note: MercadoPago Chile can generate test credentials that start with APP_USR-
# So we'll be more flexible with the validation
if MERCADOPAGO_ACCESS_TOKEN:  # Only validate if token exists
    if MERCADOPAGO_SANDBOX:
        # Accept both TEST- and APP_USR- for sandbox mode (Chile specific)
        if not (MERCADOPAGO_ACCESS_TOKEN.startswith('TEST-') or MERCADOPAGO_ACCESS_TOKEN.startswith('APP_USR-')):
            raise ValueError("MERCADOPAGO_ACCESS_TOKEN must start with 'TEST-' or 'APP_USR-' when MERCADOPAGO_SANDBOX is True")

    if not MERCADOPAGO_SANDBOX and not MERCADOPAGO_ACCESS_TOKEN.startswith('APP_USR-'):
        raise ValueError("MERCADOPAGO_ACCESS_TOKEN must start with 'APP_USR-' when MERCADOPAGO_SANDBOX is False")