# Generated by Django 5.2.6 on 2025-10-30 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendabarber', '0003_remove_reserva_fecha_remove_reserva_hora_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='barbero',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Usuario asociado a este barbero', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
