# Generated by Django 4.2.6 on 2025-11-04 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendabarber', '0004_barbero_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada'), ('Completada', 'Completada')], default='Completada', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='pagado',
            field=models.BooleanField(default=True),
        ),
    ]
