# Generated by Django 4.2.6 on 2025-11-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendabarber', '0005_alter_reserva_estado_alter_reserva_pagado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada'), ('Completada', 'Completada')], default='Pendiente', max_length=20),
        ),
    ]
