# Generated by Django 4.2.6 on 2025-11-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendabarber', '0006_alter_reserva_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbero',
            name='foto',
            field=models.CharField(blank=True, help_text='Ruta de la foto', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='imagen',
            field=models.CharField(blank=True, help_text='Ruta de la imagen', max_length=200, null=True),
        ),
    ]
