# Generated by Django 4.2.6 on 2025-11-06 01:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('agendabarber', '0006_alter_reserva_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_payment_id', models.CharField(help_text='ID único del pago en MercadoPago', max_length=100, unique=True)),
                ('mp_preference_id', models.CharField(help_text='ID de preferencia de MercadoPago', max_length=100)),
                ('mp_merchant_order_id', models.CharField(blank=True, help_text='ID de orden comercial de MercadoPago', max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto del pago', max_digits=10)),
                ('currency', models.CharField(default='CLP', help_text='Moneda del pago', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('authorized', 'Autorizado'), ('in_process', 'En Proceso'), ('in_mediation', 'En Mediación'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado'), ('charged_back', 'Contracargo')], help_text='Estado del pago en MercadoPago', max_length=20)),
                ('status_detail', models.CharField(blank=True, help_text='Detalle del estado del pago', max_length=100, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('credit_card', 'Tarjeta de Crédito'), ('debit_card', 'Tarjeta de Débito'), ('bank_transfer', 'Transferencia Bancaria'), ('cash', 'Efectivo'), ('digital_wallet', 'Billetera Digital'), ('other', 'Otro')], help_text='Método de pago utilizado', max_length=50, null=True)),
                ('payment_type', models.CharField(blank=True, help_text='Tipo de pago específico de MercadoPago', max_length=50, null=True)),
                ('external_reference', models.CharField(blank=True, help_text='Referencia externa para tracking', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Descripción del pago', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mp_date_created', models.DateTimeField(blank=True, help_text='Fecha de creación en MercadoPago', null=True)),
                ('mp_date_approved', models.DateTimeField(blank=True, help_text='Fecha de aprobación en MercadoPago', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='payment_method',
            field=models.CharField(default='mercadopago', help_text='Método de pago utilizado', max_length=50),
        ),
        migrations.CreateModel(
            name='TemporaryReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(help_text='Clave de sesión del usuario', max_length=40)),
                ('inicio', models.DateTimeField(help_text='Hora de inicio de la reserva temporal')),
                ('fin', models.DateTimeField(help_text='Hora de fin de la reserva temporal')),
                ('cliente_email', models.EmailField(help_text='Email del cliente para la reserva', max_length=254)),
                ('cliente_nombre', models.CharField(help_text='Nombre del cliente', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Momento en que expira el bloqueo temporal')),
                ('mp_preference_id', models.CharField(blank=True, help_text='ID de preferencia de MercadoPago', max_length=100, null=True)),
                ('barbero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendabarber.barbero')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendabarber.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID único para este webhook log', unique=True)),
                ('topic', models.CharField(choices=[('payment', 'Pago'), ('merchant_order', 'Orden Comercial'), ('plan', 'Plan'), ('subscription', 'Suscripción'), ('invoice', 'Factura'), ('point_integration_wh', 'Integración Point'), ('other', 'Otro')], help_text='Tipo de notificación recibida', max_length=50)),
                ('resource_id', models.CharField(help_text='ID del recurso notificado (payment_id, etc.)', max_length=100)),
                ('request_method', models.CharField(default='POST', max_length=10)),
                ('request_headers', models.JSONField(default=dict, help_text='Headers HTTP de la request')),
                ('request_body', models.JSONField(default=dict, help_text='Cuerpo de la request recibida')),
                ('request_query_params', models.JSONField(default=dict, help_text='Parámetros de query de la URL')),
                ('processing_status', models.CharField(choices=[('received', 'Recibido'), ('processing', 'Procesando'), ('processed', 'Procesado'), ('failed', 'Falló'), ('ignored', 'Ignorado'), ('duplicate', 'Duplicado')], default='received', help_text='Estado del procesamiento del webhook', max_length=20)),
                ('processing_error', models.TextField(blank=True, help_text='Error ocurrido durante el procesamiento', null=True)),
                ('processing_attempts', models.PositiveIntegerField(default=0, help_text='Número de intentos de procesamiento')),
                ('source_ip', models.GenericIPAddressField(blank=True, help_text='IP de origen del webhook', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User-Agent del webhook', null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='Momento en que se recibió el webhook')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Momento en que se procesó exitosamente', null=True)),
                ('payment_transaction', models.ForeignKey(blank=True, help_text='Transacción de pago relacionada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='agendabarber.paymenttransaction')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='reserva',
            field=models.OneToOneField(blank=True, help_text='Reserva final creada después del pago exitoso', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transaction', to='agendabarber.reserva'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='temp_reservation',
            field=models.ForeignKey(blank=True, help_text='Reserva temporal asociada', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='agendabarber.temporaryreservation'),
        ),
        migrations.AddIndex(
            model_name='temporaryreservation',
            index=models.Index(fields=['expires_at'], name='agendabarbe_expires_18c930_idx'),
        ),
        migrations.AddIndex(
            model_name='temporaryreservation',
            index=models.Index(fields=['barbero', 'inicio'], name='agendabarbe_barbero_d809cb_idx'),
        ),
        migrations.AddIndex(
            model_name='temporaryreservation',
            index=models.Index(fields=['session_key'], name='agendabarbe_session_daf941_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='temporaryreservation',
            unique_together={('barbero', 'inicio')},
        ),
        migrations.AddIndex(
            model_name='paymentwebhooklog',
            index=models.Index(fields=['topic', 'resource_id'], name='agendabarbe_topic_e17244_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhooklog',
            index=models.Index(fields=['processing_status'], name='agendabarbe_process_18a4d4_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhooklog',
            index=models.Index(fields=['received_at'], name='agendabarbe_receive_2181bf_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhooklog',
            index=models.Index(fields=['source_ip'], name='agendabarbe_source__54bcdc_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['mp_payment_id'], name='agendabarbe_mp_paym_c1e857_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['mp_preference_id'], name='agendabarbe_mp_pref_bbec3c_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status'], name='agendabarbe_status_03bc2e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['created_at'], name='agendabarbe_created_cea284_idx'),
        ),
    ]
