# Generated by Django 4.2.6 on 2025-11-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendabarber', '0007_alter_barbero_foto_alter_servicio_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbero',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='barberos/'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='servicios/'),
        ),
    ]
