# Generated by Django 4.2.6 on 2025-11-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendabarber', '0007_paymenttransaction_reserva_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
