# Generated by Django 4.2.6 on 2025-11-07 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendabarber', '0008_alter_barbero_foto_alter_servicio_imagen'),
        ('agendabarber', '0008_alter_reserva_pagado'),
    ]

    operations = [
    ]
